galaxy_info:
  author: aliho
  description: Up and running wordpress as docker container

  license: MIT

  min_ansible_version: '2.1'

  platforms:
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - wordpress
    - docker

dependencies: []
