---
- name: Setup servers
  hosts: servers
  become: true
  pre_tasks:
    - name: Update repositories
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400

  roles:
    - common
