---
- name: Setup servers
  hosts: webservers
  become: true
  pre_tasks:
    - name: Update repositories
      ansible.builtin.apt:
        update_cache: true
        # cache_valid_time: 3600

  roles:
    - role: common
      tags: [common]
    - role: docker
      tags: [docker]
    - role: wordpress
      tags: [wordpress]
    - role: nginx
      tags: [nginx]

  vars:
    base_domain: test.dev
    registry_domain: 'reg.{{ base_domain }}'
    wordpress_domain: 'wp.{{ base_domain }}'
    base_dir: /srv
    self_signed_certificate: true
