galaxy_info:
  author: aliho
  description: Up and running Nginx docker container

  license: Apache-2.0

  min_ansible_version: '2.1'

  platforms:
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - docker
    - nginx

dependencies: []
