---
common_iptables_flushed: false

common_iptables_flush_chains:
  - INPUT
  - OUTPUT

common_iptables_allow_ports:
  - { port: 22, protocol: tcp, chain: INPUT, comment: 'ssh port' }
  - { port: 22, protocol: tcp, chain: OUTPUT, comment: 'ssh port' }

common_packages:
  - iptables-persistent
  - python3-pip
  - python3-virtualenv
  - python3-setuptools
