---
docker_conflict_packages:
  - docker.io
  - docker-doc
  - docker-compose
  - podman-docker
  - containerd
  - runc

docker_depend_packages:
  - curl
  - gnupg
  - ca-certificates

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_pip_packages:
  - docker

docker_data_disk: /dev/sdb

docker_daemon_data_root_dir: /mnt/data

docker_daemon_log_driver: json-file

docker_daemon_log_opts:
  max-size: 10m
  max-file: '3'

docker_daemon_registry_mirrors: ['https://{{ registry_domain }}']

docker_registry_users:
  - name: userone
    password: '1234'

docker_registry_base_dir: '{{ base_dir }}/registry'

docker_registry_sub_dirs: ['data']

docker_registry_config_auth_enabled: false

docker_registry_config_auth_htpasswd_realm: registry

docker_registry_config_http_port: 5000

docker_registry_config_proxy_remoteurl: https://registry-1.docker.io

docker_registry_config_storage_fs_root_dir: /data

docker_users: ['vagrant']
