---
- name: Remove all conflicting packages
  ansible.builtin.apt:
    name: '{{ docker_conflict_packages }}'
    state: absent
    purge: true

- name: Remove docker lib directory
  ansible.builtin.file:
    path: /var/lib/docker
    state: absent

- name: Install dependent packages
  ansible.builtin.apt:
    name: '{{ docker_depend_packages }}'
    state: present

- name: Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add GPG key
  ansible.builtin.shell:
  executable: /bin/bash
  cmd: |
    set -o pipefail
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg chmod a+r /etc/apt/keyrings/docker.gpg
  register: output

- name: Add repository to sources
  ansible.builtin.shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" > /etc/apt/sources.list.d/docker.list
  register: output
  changed_when: output.rc != 0

- name: Install docker packages
  ansible.builtin.apt:
    name: '{{ docker_packages }}'
    state: present
    update_cache: true
  notify:
    - Enable docker service
    - Restart docker service

- name: Add users to docker group
  ansible.builtin.user:
    name: '{{ docker_users }}'
    groups: docker
    append: true
