---
- name: Include docker installation tasks
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      become: true
      tags:
        - install
  tags:
    - always

- name: Include docker configuration tasks
  ansible.builtin.include_tasks:
    file: configure.yml
    apply:
      become: true
      tags:
        - configure
  tags:
    - always

- name: Include docker registry tasks
  ansible.builtin.include_tasks:
    file: registry.yml
    apply:
      become: true
      tags:
        - registry
  tags:
    - always
